---
# - name: trigger initial system wide update (Debian)
#  apt:
#    upgrade: yes
#  when: ansible_os_family == 'Debian'

# - name: trigger initial system wide update (CentOS 7)
#  yum:
#    name: '*'
#    state: latest
#  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "7"

# - name: trigger initial system wide update (CentOS 8+)
#  dnf:
#    name: '*'
#    state: latest
#  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] >= "8"  

- name: Set timezone
  community.general.timezone:
    name: Asia/Barnaul
    
- name: Install required package
  package:
    name:
    - net-tools
    - curl
    - wget
    - nano
    - vim
    - mc
    state: present

- name: Install bmon (for Ubuntu/Debian)
  package:
    name:
    - bmon
    state: present
  when: ansible_os_family == 'Debian'

- name: Enable EPEL Repository on CentOS 8 or 9
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] >= "8" 

- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: latest
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == "7"  